name: lru_memory_cache
description: LRUMemoryCache is a Dart library for in-memory LRU caching with expiration support. Cache key-value pairs, managing eviction of least recently used items upon reaching capacity.
version: 1.0.0
repository: https://github.com/bruc3balo/LRUMemoryCache.git

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
