name: lru_memory_cache
description: LRUMemoryCache is a Dart library that provides a simple, in-memory, least recently used (LRU) caching mechanism with expiration support. It allows you to cache key-value pairs, automatically managing the eviction of least recently used items when the cache reaches its capacity.
version: 1.0.0
repository: https://github.com/bruc3balo/LRUCache.git

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
